global
    daemon
    log stdout local0 info
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy

defaults
    mode tcp
    log global
    timeout connect 5000ms
    timeout client 50000ms
    timeout server 50000ms
    option tcplog

# Kubernetes API Frontend
frontend k8s-api
    bind *:6443
    mode tcp
    default_backend k8s-masters

# Kubernetes API Backend
backend k8s-masters
    mode tcp
    balance roundrobin
    option tcp-check
    # Замініть на вашу внутрішню IP Minikube
    server minikube-master 192.168.49.2:8443 check

frontend stats
    bind *:8404
    mode http
    stats enable
    #stats hide-version
    stats uri /stats
    stats realm Haproxy\ Statistics
    stats auth admin:YourSecurePassword
    # Or use an ACL for IP-based access:
    # acl LOCALHOST src 127.0.0.1/32
    # stats admin if LOCALHOST
    stats refresh 10s
    stats admin if TRUE