---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: minikube-ingress-dns
  namespace: kube-system
  labels:
    app: minikube-ingress-dns
    kubernetes.io/bootstrapping: rbac-defaults
    app.kubernetes.io/part-of: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: minikube-ingress-dns
  namespace: kube-system
  labels:
    app: minikube-ingress-dns
    kubernetes.io/bootstrapping: rbac-defaults
    app.kubernetes.io/part-of: kube-system
    gcp-auth-skip-secret: "true"
rules:
  - apiGroups:
      - ""
      - "extensions"
      - "networking.k8s.io"
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: minikube-ingress-dns
  namespace: kube-system
  labels:
    app: minikube-ingress-dns
    kubernetes.io/bootstrapping: rbac-defaults
    app.kubernetes.io/part-of: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: minikube-ingress-dns
subjects:
  - kind: ServiceAccount
    name: minikube-ingress-dns
    namespace: kube-system
---
apiVersion: v1
kind: Pod
metadata:
  name: kube-ingress-dns-minikube
  namespace: kube-system
  labels:
    app: minikube-ingress-dns
    app.kubernetes.io/part-of: kube-system
spec:
  serviceAccountName: minikube-ingress-dns
  hostNetwork: true
  containers:
    - name: minikube-ingress-dns
      image: "gitlabprozorro/minikube-ingress-dns:0.3.1"
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 53
          protocol: UDP
      env:
        - name: DNS_PORT
          value: "53"
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP